/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blok.gui;

import blok.AbstractFactory.IThemeFactory;
import blok.simulator.Simulator;
import java.awt.Dimension;
import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;

/**
 *
 * @author sandroandrade
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
    	initComponents();
        Dimension size = new Dimension(1000, 600);

        mainPanel = new MainPanel(factory);
        mainPanel.setPreferredSize(size);
        mainPanel.setMinimumSize(size);
        mainPanel.setMaximumSize(size);
        mainPanel.setSize(size);
        setContentPane(mainPanel);

        setResizable(false);
        pack();
        
        simulator = new Simulator(mainPanel);
        mainPanel.setSimulator(simulator);
        simulator.init();
        //simulator.start();
    }
    
	@SuppressWarnings("deprecation")
    private void loadPlugins() {
        try {
            File currentDir = new File("./plugins");
            String[] plugins = currentDir.list();
            URL[] jars = new URL[plugins.length];
            javax.swing.JMenuItem[] menus = new javax.swing.JMenuItem[plugins.length];
            for(int i = 0; i < plugins.length; i++) {
                    String classe = plugins[i].split("\\.")[0];
                    System.out.println(i+1 + " - " + classe);
                    menus[i] = new javax.swing.JMenuItem();
                    menus[i].setText(classe);
                           menus[i].addActionListener(new java.awt.event.ActionListener(){
                               @Override
                               public void actionPerformed(java.awt.event.ActionEvent evt){
                                   jMenusActionPerformed(evt);
                               }
                           });
                    this.jMenu1.add(menus[i]);
                    jars[i] = (new File("./plugins/"+ plugins[i])).toURL();
            }
            this.ulc = new URLClassLoader(jars);
            String nomeClasse = plugins[0].split("\\.")[0];
            this.factory = (IThemeFactory)Class.forName("blok."+nomeClasse.toLowerCase()
            +"."+nomeClasse,true,ulc).newInstance();
            } catch(Exception e) {
    		System.out.println(e);
            }
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        
        loadPlugins();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenusActionPerformed(java.awt.event.ActionEvent evt){
        try{
            String nomeClasse = evt.getActionCommand();
              System.out.println(nomeClasse);
            IThemeFactory factory = (IThemeFactory)Class.forName("blok."+nomeClasse.toLowerCase()
            +"."+nomeClasse,true,ulc).newInstance();
            initComponents();
        }catch(ClassNotFoundException e){
            System.out.println(e);
        } catch (InstantiationException e) {
            System.out.println(e);
        } catch (IllegalAccessException e) {
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
    private IThemeFactory factory;
    private URLClassLoader ulc;
    private MainPanel mainPanel;
    Simulator simulator;
}
